### ISSUE TITLE
判断操作系统出错了

### ISSUE THREAD

**Issue by cauchyah** [smallSohoSolo/McImage#24]
![image](https://user-images.githubusercontent.com/17943988/60788432-4c0fa600-a18f-11e9-9324-e91d62b6ab65.png)
**System.getProperty("os.name")** 在我的机器上会返回**Windows 7** 以致不走任何case 直接return了。可以考虑用startWith或contain来判断

**Comment by smallSohoSolo** [comment]
这个目前根据win10适配的。。。win7停更了，暂时不修复。。
