### ISSUE TITLE
操作源文件

### ISSUE THREAD

**Issue by ywqian** [smallSohoSolo/McImage#25]
hello，你好，这样操作的文件是不是还是项目源文件的资源图片？如果想不修改源文件的图片，仅仅是在apk中是压缩后的图片，aapt2的方式是不是不行？

**Comment by smallSohoSolo** [comment]
如果关掉aapt2，用0.1.5的版本可以做到完全无侵入。
aapt2的构建方式改了，跟aapt不一样，目前hook方案暂时做不到对源文件的完全无修改。可以在ci上配置个git reset命令在构建之后回滚图片。

**Comment by ywqian** [comment]
你好，谢谢，另外想咨询下，那如果在packageDebug后解压apk，对图片做压缩或者webp转换的话，那对应的resources.arsc文件需要做相应的改动吗？

**Comment by smallSohoSolo** [comment]
你在那个阶段拿不到源文件了，拿到的都是aapt2处理之后的文件，我没试过
aapt2还原 -> 压缩 -> aapt2在处理 这种操作
简单看gradle构建代码貌似不行，你可以试试

**Comment by ywqian** [comment]
嗯，好的，其实我是想像微信资源混淆一样，解压apk，对apk中的图片进行压缩或者webp转化，然后再重新打包，不过就是不知道这样做需要不需要修改resources.arsc中的一些东西；

**Comment by smallSohoSolo** [comment]
我觉得可以研究一下微信资源混淆，然后试试看能否做到完全无侵入，我没看过微信的代码所以不能下结论。

**Comment by ywqian** [comment]
好的，谢谢大神，另外我看到获取mergeResources的inputs.files应该也是可以获取到资源图片输入文件的，应该可以不用通过hook的方式。
