### ISSUE TITLE
mctools 找不到

### ISSUE THREAD

**Issue by lijiankun24** [smallSohoSolo/McImage#27]
在源码中未能找到 mctools，是哪里不对么

**Comment by smallSohoSolo** [comment]
在release 里面找哈，readme里面有链接

**Comment by lijiankun24** [comment]
还是没找到 mctools dir，能否截个图示意一下

**Comment by smallSohoSolo** [comment]
https://github.com/smallSohoSolo/McImage/releases/tag/v1.0.1
