### ISSUE TITLE
如何主持aar里面的图片进行webp转换呢？

### ISSUE THREAD

**Issue by tyh470075227** [smallSohoSolo/McImage#30]
我们的很多module都是aar模式，这种情况下webp转换就基本没啥效果了

**Comment by smallSohoSolo** [comment]
webp只是优化的一环，还有其他的优化，能小很多。
其实其他的优化占百分之90，webp只是让这个优化更极致

**Comment by smallSohoSolo** [comment]
全量webp的方案需要您的app min sdk >= 18 不然低版本会crash，如果您满足这个条件可以使用compressweb，这个是最大效率的压缩，能小很多。
