### ISSUE TITLE
gradle版本兼容问题

### ISSUE THREAD

**Issue by 1004145468** [smallSohoSolo/McImage#32]
在v1.5.0版本里面没有见有做过gradle版本兼容处理，岂不是在低版本里面会出现问题，比如'com.android.tools.build:gradle:3.1.4'

兼容问题：
* What went wrong:
A problem occurred configuring project ':app'.
> Could not find method getMergeResourcesProvider() for arguments [] on object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.

**Comment by smallSohoSolo** [comment]
低版本，请使用低版本mcimage
