### ISSUE TITLE
直接修改原始的文件, 包括aar?

### ISSUE THREAD

**Issue by kexuejin** [smallSohoSolo/McImage#33]
这是很危险的操作吧?  为什么不是修改中间文件.

**Comment by smallSohoSolo** [comment]
如果关闭aapt2是修改中间产物的，但是aapt2的整个构建过程导致暂时没有找到hook点来解决，并且修改中间产物较慢，所以没有修改中间产物，另外并不危险，此产品已经稳定运行在某上亿dau产品2年，无任何问题
