### ISSUE TITLE
需要每个module都apply plugin吗

### ISSUE THREAD

**Issue by Kyson** [smallSohoSolo/McImage#34]
是不是只要最后打apk的合并资源task之前做压缩，application模块依赖就可以了？
另外压缩结果文件可以输出吗？

**Comment by Kyson** [comment]
![image](https://user-images.githubusercontent.com/3901140/75854261-c382fb80-5e2a-11ea-94ab-f0f08b60a23c.png)
这个注释和代码不匹配？

是要assemble的任务可以执行下去还是不能执行下去？

**Comment by smallSohoSolo** [comment]
需要每个module都apply，另外压缩结果文件用log输出了，可以过滤McImage查看
这个注视的意思是如果是构建release包才执行，因为task可能有很多种情况，一般情况执行压缩没有必要
这里”assemble“ 有点歧义，应该是“release”，可以看上面的代码，分别判断了assembleRelease，resguardRelease，bundle（打app bundle）的情况

**Comment by Kyson** [comment]
> 是不是只要最后打apk的合并资源task之前做压缩，application模块依赖就可以了？

我问这个的意思是技术上可不可以做成这样，这样会方便很多，尤其对大型项目来说

另外我看到的master分支的代码就是不包含‘assemble’就不执行了

![image](https://user-images.githubusercontent.com/3901140/75856732-e82da200-5e2f-11ea-9ed1-28525b5563f9.png)

**Comment by smallSohoSolo** [comment]
是这样的，因为不同的module构建树不一样，暂时没找到合适的插入点（主要原因），尝试找过应该不支持，不符合gradle设计思路，因为每个module是自己打包自己，然后到最后是一个aar了，无法聚合处理资源，另外并不是所有的module都需要压缩哈

**Comment by Kyson** [comment]
@smallSohoSolo 谢谢解答，另外最好把压缩的命令提供一些参数出来，现在是有损压缩

**Comment by smallSohoSolo** [comment]
经过专业设计验证，目前的压缩方案是调整过的，如果有更强的自定义，可以自行修复源码哈，但是我们在上亿的设备上验证之后还是目前的参数更加优秀
