### ISSUE TITLE
Cause: sourceImg must not be null

### ISSUE THREAD

**Issue by wangjing71** [smallSohoSolo/McImage#40]
Cause: sourceImg must not be null

**Comment by smallSohoSolo** [comment]
请补充更多的信息进来，感谢

**Comment by wangjing71** [comment]
按照步骤集成出现这个提示
---- McImage Plugin Start ----
<<<<<<<<<<<<<<McConfig>>>>>>>>>>>>
maxSize :1048576.0
isCheckSize: true
optimizeType: ConvertWebp
enableWhenDebug: true
isCheckPixels: true
maxWidth: 1000, maxHeight: 1000
mctoolsDir: 
isSupportAlphaWebp: false
multiThread: true
whiteList : 
bigImageWhiteList: 
<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>

> Task :busihall_v30:McImageDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':busihall_v30:McImageDebug'.
> sourceImg must not be null

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
31 actionable tasks: 31 executed

**Comment by smallSohoSolo** [comment]
您的工程 魔改 gradle 了是吗？ 看上去不是按照规范使用的
