### ISSUE TITLE
windows cwebp error

### ISSUE THREAD

**Issue by vulturelan** [smallSohoSolo/McImage#42]
使用mctools/windows中的cwebp压缩png，报错：
cmd: cwebp xxx.png -o xxx.webp -m 6
CoCreateInstance(MAKE_REFGUID(CLSID_WICImagingFactory), NULL, CLSCTX_INPROC_SERV
ER, MAKE_REFGUID(IID_IWICImagingFactory), (LPVOID*)&factory) failed 80040154
Couldn't access Windows Imaging Component (are you running Windows XP SP3 or new
er?). Most formats not available. Use -s for the available YUV input.
报错后根据 webpFile.length() < imgFile.length()，会将原png图片删除，而webp图片未成功生成，打包时造成资源缺失

使用 libwebp-1.1.0-windows-x64-no-wic.zip 带no-wic的库后压缩成功。

**Comment by smallSohoSolo** [comment]
不好意思，实在是没有win 环境测试，所以win 下的压缩没有测试，可能是库的问题
