### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by IanChengYuen** [smallSohoSolo/McImage#43]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > com.android.build.gradle.internal.api.BaseVariantImpl.getMergeResourcesProvider()Lorg/gradle/api/tasks/TaskProvider;

**Comment by smallSohoSolo** [comment]
请使用低版本，高版本 gradle 要求 3.5.0以上，readme 有说明
