### ISSUE TITLE
优化出现负数了

### ISSUE THREAD

**Issue by ymangu163** [smallSohoSolo/McImage#44]
优化出现负数了
![image](https://user-images.githubusercontent.com/9247244/78766796-4e23c100-79bc-11ea-985a-0ef95a4be6cd.png)

**Comment by smallSohoSolo** [comment]
麻烦帮忙确认下是否 有优化？
然后我这边确认下是 数字计算问题还是 压缩问题

**Comment by tokiii** [comment]
> 优化出现负数了
> ![image](https://user-images.githubusercontent.com/9247244/78766796-4e23c100-79bc-11ea-985a-0ef95a4be6cd.png)

你的   optimizeType:ConvertWebp  写错了

**Comment by smallSohoSolo** [comment]
我检查了下代码，应该是您这边写错了。。。
