### ISSUE TITLE
sourceImg must not be null 出现了这个问题，无法定位

### ISSUE THREAD

**Issue by i-show** [smallSohoSolo/McImage#46]
> Task :app:McImageRelease FAILED
---- McImage Plugin Start ----
<<<<<<<<<<<<<<McConfig>>>>>>>>>>>>
maxSize :1048576.0
isCheckSize: true
optimizeType: ConvertWebp
enableWhenDebug: false
isCheckPixels: true
maxWidth: 1000, maxHeight: 1000
mctoolsDir: /Users/xxx/Workspace/android/dev/xxx
isSupportAlphaWebp: false
multiThread: true
whiteList : 
bigImageWhiteList: 
<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:McImageRelease'.
> sourceImg must not be null

**Comment by smallSohoSolo** [comment]
麻烦提供gradle版本和mcimage版本，我复线一下

**Comment by i-show** [comment]
> 麻烦提供gradle版本和mcimage版本，我复线一下

已经不使用了，谢谢
