### ISSUE TITLE
请问一下为什么我打包后module里面的packaged_res已经转换为了webp，但是最终apk里面却还是png？

### ISSUE THREAD

**Issue by leigao109** [smallSohoSolo/McImage#47]
看McImage日志也没什么问题。

另外是否支持指定某个module使用McImage？

**Comment by smallSohoSolo** [comment]
某个module 需要单独apply plugin 就行了，支持的，可以检查一下是否使用正确，另外是否魔改了gradle

**Comment by leigao109** [comment]
不知道为什么在本地打包的时候最终`apk`图片没有改变，但是用`Jenkins`打包发现转为`WebP `了。另外支持`assets`文件夹里面的图片进行压缩吗？

**Comment by yezhichao** [comment]
遇到了一样的问题，看各个module/build/intermediates/packaged_res/ 里面的图片都已经转换了，但是打出来的debug包一看全是png

**Comment by biginsect** [comment]
@yezhichao 你是不是没有设置enableWhenDebug 这个开关啊。

**Comment by biginsect** [comment]
@yezhichao 
McImageConfig {
    isCheckSize true //是否检测图片大小，默认为true
    optimizeType "ConvertWebp" //优化类型，可选"ConvertWebp"，"Compress"，转换为webp或原图压缩，默认Compress，使用ConvertWep需要min sdk >= 18.但是压缩效果更好
    enableWhenDebug true //debug下是否可用，default true
    isCheckPixels true // 是否检测大像素图片，default true
    maxWidth 1000 //default 1000 如果开启图片宽高检查，默认的最大宽度
    maxHeight 1000 //default 1000 如果开启图片宽高检查，默认的最大高度
    whiteList = [ //默认为空，如果添加，对图片不进行任何处理
                  "icon_launcher.png"
    ]
    mctoolsDir "$rootDir"
    isSupportAlphaWebp true  //是否支持带有透明度的webp，default false,带有透明图的图片会进行压缩
    multiThread true  //是否开启多线程处理图片，default true
    bigImageWhiteList = ['ic_mi_tv.png','ic_mi_tv_state.png','home_ad_1.png','top_tv_bg.png'] //默认为空，如果添加，大图检测将跳过这些图片
}

我配置是这样的，但是项目里面的PNG并没有在打包的时候转成webp，不知道是哪里出了问题。

**Comment by yezhichao** [comment]
@biginsect 
module/build/intermediates/packaged_res/debug/ 这里面的drawable目录里图片有转换成webp吗？

**Comment by biginsect** [comment]
@yezhichao 我写了一个小demo  部分系统自带的png确实被转成了webp，但是我从别的地方拿过来的图片就没有转，提示 
 [Webp][E:\android demo\ImageOptimizationDemo\app\src\main\res\drawable-xxhdpi\icon_picture.png][oldInfo: 181899][newInfo: 0]。。
实在是不清楚哪里配置错了

**Comment by smallSohoSolo** [comment]
debug 被过滤了，请用release 尝试，另外配置里面有debug是否过滤，这个默认是过滤，大佬们看下是否正确

**Comment by yanchunlan** [comment]
我也遇到了一样的问题

**Comment by nianzixin** [comment]
我也遇到了一样的问题，按照文档接入了，直接run的包和jenkins的包都没有转成webP

**Comment by smallSohoSolo** [comment]
统一回复，assets 里面没有进行转换，原因是assets 过于灵活，转换风险高
