### ISSUE TITLE
为什么要下载McTool

### ISSUE THREAD

**Issue by wangrunxiang** [smallSohoSolo/McImage#49]
为什么要下载McTool文件夹，直接拉webp的源码或者用libwebp.so来转码不好吗？

**Comment by smallSohoSolo** [comment]
适配mac linux windows

**Comment by wangrunxiang** [comment]
libwebp.so这种操作，连适配都不用吧，直接代码给你跑了

**Comment by smallSohoSolo** [comment]
这个命令行更加简单，确实so更好，大佬有机会可以来个pr
