### ISSUE TITLE
apply plugin存在报错

### ISSUE THREAD

**Issue by wangrunxiang** [smallSohoSolo/McImage#50]
>A problem occurred configuring project ':home'.
> Could not determine the dependencies of task ':home:mergeDebugResources'.
   > Could not resolve all dependencies for configuration ':home:debugRuntimeClasspath'.
      > A problem occurred configuring project ':home-api'.
         > Circular referencing during evaluation for project ':home'.

问一下大佬有可能是啥原因？

**Comment by smallSohoSolo** [comment]
看报错是循环引用，应该跟mcimage没什么关系。。

**Comment by wangrunxiang** [comment]
@smallSohoSolo 去掉apply plugin 'McImage'就没问题了，加上就有问题

**Comment by wangrunxiang** [comment]
@smallSohoSolo 兄弟，能否加个微信交流一下？微信号wangrunxiang1
