### ISSUE TITLE
写了个demo，好像不能处理mipmap下的东西，直接报错跑不起来

### ISSUE THREAD

**Issue by wangrunxiang** [smallSohoSolo/McImage#52]
> Task :app:mergeDebugResources FAILED
AGPBI: {"kind":"error","text":"Duplicate resources","sources":[{"file":{"description":"mipmap-hdpi-v4/ic_launcher","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-hdpi\\ic_launcher.png"}},{"file":{"description":"mipmap-hdpi-v4/ic_launcher","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-hdpi\\ic_launcher.webp"}}],"tool":"Resource and asset merger"}
AGPBI: {"kind":"error","text":"Duplicate resources","sources":[{"file":{"description":"mipmap-hdpi-v4/ic_launcher_round","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-hdpi\\ic_launcher_round.png"}},{"file":{"description":"mipmap-hdpi-v4/ic_launcher_round","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-hdpi\\ic_launcher_round.webp"}}],"tool":"Resource and asset merger"}
AGPBI: {"kind":"error","text":"Duplicate resources","sources":[{"file":{"description":"mipmap-mdpi-v4/ic_launcher","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-mdpi\\ic_launcher.png"}},{"file":{"description":"mipmap-mdpi-v4/ic_launcher","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-mdpi\\ic_launcher.webp"}}],"tool":"Resource and asset merger"}
AGPBI: {"kind":"error","text":"Duplicate resources","sources":[{"file":{"description":"mipmap-mdpi-v4/ic_launcher_round","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-mdpi\\ic_launcher_round.png"}},{"file":{"description":"mipmap-mdpi-v4/ic_launcher_round","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-mdpi\\ic_launcher_round.webp"}}],"tool":"Resource and asset merger"}
AGPBI: {"kind":"error","text":"Duplicate resources","sources":[{"file":{"description":"mipmap-xhdpi-v4/ic_launcher","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-xhdpi\\ic_launcher.png"}},{"file":{"description":"mipmap-xhdpi-v4/ic_launcher","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-xhdpi\\ic_launcher.webp"}}],"tool":"Resource and asset merger"}
AGPBI: {"kind":"error","text":"Duplicate resources","sources":[{"file":{"description":"mipmap-xhdpi-v4/ic_launcher_round","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-xhdpi\\ic_launcher_round.png"}},{"file":{"description":"mipmap-xhdpi-v4/ic_launcher_round","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-xhdpi\\ic_launcher_round.webp"}}],"tool":"Resource and asset merger"}
AGPBI: {"kind":"error","text":"Duplicate resources","sources":[{"file":{"description":"mipmap-xxhdpi-v4/ic_launcher","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-xxhdpi\\ic_launcher.png"}},{"file":{"description":"mipmap-xxhdpi-v4/ic_launcher","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-xxhdpi\\ic_launcher.webp"}}],"tool":"Resource and asset merger"}
AGPBI: {"kind":"error","text":"Duplicate resources","sources":[{"file":{"description":"mipmap-xxhdpi-v4/ic_launcher_round","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-xxhdpi\\ic_launcher_round.png"}},{"file":{"description":"mipmap-xxhdpi-v4/ic_launcher_round","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-xxhdpi\\ic_launcher_round.webp"}}],"tool":"Resource and asset merger"}
AGPBI: {"kind":"error","text":"Duplicate resources","sources":[{"file":{"description":"mipmap-xxxhdpi-v4/ic_launcher","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-xxxhdpi\\ic_launcher.png"}},{"file":{"description":"mipmap-xxxhdpi-v4/ic_launcher","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-xxxhdpi\\ic_launcher.webp"}}],"tool":"Resource and asset merger"}
AGPBI: {"kind":"error","text":"Duplicate resources","sources":[{"file":{"description":"mipmap-xxxhdpi-v4/ic_launcher_round","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-xxxhdpi\\ic_launcher_round.png"}},{"file":{"description":"mipmap-xxxhdpi-v4/ic_launcher_round","path":"D:\\AndroidStudioProjects\\McImageDemo\\app\\src\\main\\res\\mipmap-xxxhdpi\\ic_launcher_round.webp"}}],"tool":"Resource and asset merger"}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> [mipmap-hdpi-v4/ic_launcher] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-hdpi\ic_launcher.png	[mipmap-hdpi-v4/ic_launcher] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-hdpi\ic_launcher.webp: Error: Duplicate resources
  [mipmap-hdpi-v4/ic_launcher_round] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-hdpi\ic_launcher_round.png	[mipmap-hdpi-v4/ic_launcher_round] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-hdpi\ic_launcher_round.webp: Error: Duplicate resources
  [mipmap-mdpi-v4/ic_launcher] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-mdpi\ic_launcher.png	[mipmap-mdpi-v4/ic_launcher] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-mdpi\ic_launcher.webp: Error: Duplicate resources
  [mipmap-mdpi-v4/ic_launcher_round] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-mdpi\ic_launcher_round.png	[mipmap-mdpi-v4/ic_launcher_round] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-mdpi\ic_launcher_round.webp: Error: Duplicate resources
  [mipmap-xhdpi-v4/ic_launcher] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-xhdpi\ic_launcher.png	[mipmap-xhdpi-v4/ic_launcher] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-xhdpi\ic_launcher.webp: Error: Duplicate resources
  [mipmap-xhdpi-v4/ic_launcher_round] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-xhdpi\ic_launcher_round.png	[mipmap-xhdpi-v4/ic_launcher_round] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-xhdpi\ic_launcher_round.webp: Error: Duplicate resources
  [mipmap-xxhdpi-v4/ic_launcher] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-xxhdpi\ic_launcher.png	[mipmap-xxhdpi-v4/ic_launcher] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-xxhdpi\ic_launcher.webp: Error: Duplicate resources
  [mipmap-xxhdpi-v4/ic_launcher_round] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-xxhdpi\ic_launcher_round.png	[mipmap-xxhdpi-v4/ic_launcher_round] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-xxhdpi\ic_launcher_round.webp: Error: Duplicate resources
  [mipmap-xxxhdpi-v4/ic_launcher] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png	[mipmap-xxxhdpi-v4/ic_launcher] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-xxxhdpi\ic_launcher.webp: Error: Duplicate resources
  [mipmap-xxxhdpi-v4/ic_launcher_round] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-xxxhdpi\ic_launcher_round.png	[mipmap-xxxhdpi-v4/ic_launcher_round] D:\AndroidStudioProjects\McImageDemo\app\src\main\res\mipmap-xxxhdpi\ic_launcher_round.webp: Error: Duplicate resources

**Comment by wangrunxiang** [comment]
isSupportAlphaWebp true的

**Comment by smallSohoSolo** [comment]
icon 不能直接压缩，会有问题，icon 请添加白名单
