### ISSUE TITLE
写了个最简单的demo

### ISSUE THREAD

**Issue by wangrunxiang** [smallSohoSolo/McImage#53]
写了个最简单的demo，然后把plugin加进去，然后拷了几十张图片进去drawable-xxhdpi，然后跑起来，到mergeDebugResource这一步报错，很多张图片Duplicate resources，到目录下看，在drawable-xxhdpi有重复名字的，但是格式不同的，所以我们这个插件是生成在原有目录下的？要我们手工去删除原来的图片？
看源码好像是有比较大小删除，但是没有成功？

McImageConfig {
    isCheckSize false //是否检测图片大小，默认为true
    optimizeType "ConvertWebp" //优化类型，可选"ConvertWebp"，"Compress"，转换为webp或原图压缩，默认Compress，使用ConvertWep需要min sdk >= 18.但是压缩效果更好
    isSupportAlphaWebp true
    whiteList = [
            "ic_launcher.png",
            "ic_launcher_round.png",
    ]
    maxWidth 5000 //default 1000
    maxHeight 5000 //default 1000
}

**Comment by smallSohoSolo** [comment]
确实会修改源文件，不过会把旧的删掉，你可以看下为什么没删掉

**Comment by wangrunxiang** [comment]
没找到为啥没删掉的原因，有可能是什么原因？

**Comment by fengyuehan** [comment]
你好，我也遇到类似的问题，我是部分转换的会把原来的删掉，但是还有部分的没有删掉，会同时存在两张不同格式的图片。

**Comment by smallSohoSolo** [comment]
注意不要在ci 执行一半的时候终止

**Comment by wangrunxiang** [comment]
@smallSohoSolo 没有办法让他自动解决吗
