### ISSUE TITLE
已经是webp格式的图片没有进行压缩

### ISSUE THREAD

**Issue by tokiii** [smallSohoSolo/McImage#55]

**Comment by biginsect** [comment]
webp的本身就被压缩过了把

**Comment by biginsect** [comment]
请教下，这个插件是打包的时候将图片压缩处理的把，但我写了个demo处理发现没有进行处理，不确定是否是因为我的配置有问题。

McImageConfig {
    isCheckSize true //是否检测图片大小，默认为true
    optimizeType "ConvertWebp" //优化类型，可选"ConvertWebp"，"Compress"，转换为webp或原图压缩，默认Compress，使用ConvertWep需要min sdk >= 18.但是压缩效果更好
    enableWhenDebug true //debug下是否可用，default true
    isCheckPixels true // 是否检测大像素图片，default true
    maxWidth 1000 //default 1000 如果开启图片宽高检查，默认的最大宽度
    maxHeight 1000 //default 1000 如果开启图片宽高检查，默认的最大高度
    whiteList = [ //默认为空，如果添加，对图片不进行任何处理
                  "icon_launcher.png"
    ]
    mctoolsDir "$rootDir"
    isSupportAlphaWebp true  //是否支持带有透明度的webp，default false,带有透明图的图片会进行压缩
    multiThread true  //是否开启多线程处理图片，default true
    bigImageWhiteList = ['ic_mi_tv.png','ic_mi_tv_state.png','home_ad_1.png','top_tv_bg.png'] //默认为空，如果添加，大图检测将跳过这些图片
}
------
mctools 我也下了放在了根目录下，log显示：
[Webp][E:\android demo\ImageOptimizationDemo\app\src\main\res\drawable-xxhdpi\home_ad_1.png][oldInfo: 115062][newInfo: 0]

**Comment by smallSohoSolo** [comment]
是个好想法，我补充一下，我找找webp压缩算法
