### ISSUE TITLE
报了一个异常

### ISSUE THREAD

**Issue by biginsect** [smallSohoSolo/McImage#56]
McImage: optimizeImage have some Exception!!!
对于module下所有的PNG图片都是报这个错误。
配置信息：
McImageConfig {
    isCheckSize true //是否检测图片大小，默认为true
    optimizeType "ConvertWebp" //优化类型，可选"ConvertWebp"，"Compress"，转换为webp或原图压缩，默认Compress，使用ConvertWep需要min sdk >= 18.但是压缩效果更好
    enableWhenDebug true //debug下是否可用，default true
    isCheckPixels true // 是否检测大像素图片，default true
    maxWidth 1000 //default 1000 如果开启图片宽高检查，默认的最大宽度
    maxHeight 1000 //default 1000 如果开启图片宽高检查，默认的最大高度
    whiteList = [ //默认为空，如果添加，对图片不进行任何处理

    ]
    mctoolsDir "$rootDir"
    isSupportAlphaWebp true  //是否支持带有透明度的webp，default false,带有透明图的图片会进行压缩
    multiThread true  //是否开启多线程处理图片，default true
    bigImageWhiteList = ['ic_mi_tv.png','ic_mi_tv_state.png','home_ad_1.png','top_tv_bg.png'] //默认为空，如果添加，大图检测将跳过这些图片
}

看了代码是没有转成功？

**Comment by smallSohoSolo** [comment]
看了下是转成webp有问题，应该是 mctools的适配问题，麻烦更换打包机器（win不稳定，最好用mac）
