### ISSUE TITLE
重复压缩可能会导致图片失真

### ISSUE THREAD

**Issue by likebamboo** [smallSohoSolo/McImage#57]
多次执行打包命令如`gradlew assembleRelease`貌似会对png等多次进行压缩，这样很可能会失真。

我看代码中似乎并没有记录已经处理过的文件、并且生成的输入的文件和输出的文件都是在同一个目录(如果选择压缩那文件名也一样，如果是转webp那就是后缀不一样)。

**Comment by smallSohoSolo** [comment]
是会重复压缩，但是代码里面判断了，如果压缩后的版本没有更小，会丢弃新的结果，所以如果打包机不换恒定是最优解。因为是有损压缩，所以失真难免，但是大体上是ok的
