### ISSUE TITLE
压缩第三方高德地图的图片出错

### ISSUE THREAD

**Issue by qwc774163019** [smallSohoSolo/McImage#61]
第三方高德AAR文件压缩时，找不到对应的图片文件
![截屏2020-10-26 15 25 49](https://user-images.githubusercontent.com/4485575/97144569-a925d580-179f-11eb-96ab-8f21e57b80e0.png)

**Comment by smallSohoSolo** [comment]
看上去是 被别的插件 优化掉了，提高mcimage的优先级，优先apply

**Comment by qwc774163019** [comment]
> 看上去是 被别的插件 优化掉了，提高mcimage的优先级，优先apply

压缩高德AAR文件时，可能这次是这张图片找不到，下次再构建就变成别的图片找不到了😂

**Comment by smallSohoSolo** [comment]
主要是图片是 gradle 标准 plugin 给到我的，用的标准api， 不应该有问题。。

**Comment by qwc774163019** [comment]
> > 看上去是 被别的插件 优化掉了，提高mcimage的优先级，优先apply
> 
> 压缩高德AAR文件时，可能这次是这张图片找不到，下次再构建就变成别的图片找不到了😂

> 主要是图片是 gradle 标准 plugin 给到我的，用的标准api， 不应该有问题。。

嗯，压我本地的图片都没问题，就是第三的会出现，我刚才试了一下优先apply，结果变成FileNotFoundException: /Users/qiwenchao/.gradle/caches/transforms-2/files-2.1/dc1a0a92df8f1a0513200e78df482037/material-1.0.0/res/drawable-hdpi-v4/design_ic_visibility_off.png (No such file or directory)

**Comment by qwc774163019** [comment]
我发现我使用./gradlew assembleReleaseTest命令行会出现这问题，但是我直接运行assembleReleaseTest是正常的

**Comment by smallSohoSolo** [comment]
讲道理这俩没啥区别。。。

**Comment by xingstarx** [comment]
别开多线程，就用单线程的配置压缩试试
