### ISSUE TITLE
config them into bigImageWhiteList to fix this Exception!!!

### ISSUE THREAD

**Issue by xuanwenchao** [smallSohoSolo/McImage#62]
这些大图片也需要做压宿、如果都加到bigImageWhiteList里面，是否就跳过不压缩这些图片了？ 要如何处理呢？ 谢谢
You have big Imgages with big size or large pixels,please confirm whether they are necessary or whether they can to be compressed. If so, you can config them into bigImageWhiteList to fix this Exception!!!
/Users/xuanwenchao/.gradle/caches/transforms-2/files-2.1/3ef5721092263fff59a97625e14540bd/jetified-facebook-login-5.15.3/res/drawable-mdpi-v4/com_facebook_profile_picture_blank_portrait.png
/Users/xuanwenchao/.gradle/caches/transforms-2/files-2.1/3ef5721092263fff59a97625e14540bd/jetified-facebook-login-5.15.3/res/drawable-mdpi-v4/com_facebook_profile_picture_blank_square.png
/Users/xuanwenchao/.gradle/caches/transforms-2/files-2.1/e6eabd2f19b43a5b354321aca5181adc/jetified-facebook-common-5.15.3/res/drawable-xxhdpi-v4/com_facebook_close.png
/Users/xuanwenchao/.gradle/caches/transforms-2/files-2.1/e6eabd2f19b43a5b354321aca5181adc/jetified-facebook-common-5.15.3/res/drawable-xhdpi-v4/com_facebook_close.png
/Users/xuanwenchao/.gradle/caches/transforms-2/files-2.1/e6eabd2f19b43a5b354321aca5181adc/jetified-facebook-common-5.15.3/res/drawable-mdpi-v4/com_facebook_close.png
/Users/xuanwenchao/.gradle/caches/transforms-2/files-2.1/e6eabd2f19b43a5b354321aca5181adc/jetified-facebook-common-5.15.3/res/drawable-hdpi-v4/com_facebook_close.png
/Users/xuanwenchao/.gradle/caches/transforms-2/files-2.1/a87b407744fc773eacf256800a420224/jetified-pinpad-1.0.4/res/drawable-xxhdpi-v4/ps_backspace.png

**Comment by yrjwcharm** [comment]
@xuanwenchao  same Error

**Comment by smallSohoSolo** [comment]
讲道理解决方案应该是手动压缩之后再放进来，如果你动不了就调高 max size的阈值
