### ISSUE TITLE
修改源文件 优化点

### ISSUE THREAD

**Issue by ruidge** [smallSohoSolo/McImage#66]
博主, 我跑了个demo试了下, 确实会将图片压缩为8bit并覆盖原文件, 现在有几个问题: 
1. 图片压缩到8bit后对图片的质量的压缩大吗, (特别是现在屏幕素质越来越高), 设计师会看出图片显示与提供的原图差别吗?
2. 现在是每构建一次就进行一次压缩, 但是感觉定时压缩(比如提测前)也够了, 这方面可以自定义或者改源码实现吗?

**Comment by smallSohoSolo** [comment]
1. 目前看设计师没反馈有什么问题
2. 定时不准，还是每次构建比较稳定，多10几秒而已，但是能保证每次都是最小的
