### ISSUE TITLE
png格式的图片不能全部删除掉，同时存在两张不同格式的图片

### ISSUE THREAD

**Issue by fengyuehan** [smallSohoSolo/McImage#67]
您好，我遇到这样的问题，部分转换的会把原来png格式的图片删掉，但是还有部分的没有删掉，会同时存在两张不同格式的图片。到mergeDebugResource这一步报错，很多张图片Duplicate resources。请问是什么原因造成这种现象，该怎么处理？

**Comment by smallSohoSolo** [comment]
如果gradle执行一半失败了，需要clean ci的工作空间（如果用的是jenkins）

**Comment by fengyuehan** [comment]
> 如果gradle执行一半失败了，需要clean ci的工作空间（如果用的是jenkins）

只是在AS上进行常规的打包而已，没有用jenkins

**Comment by huazhouwujinbiao** [comment]
我也遇到同样的问题，尝试不删除，重命名也不行，猜测是打包过程中，文件被占用了，现在我的处理方法是如果删不掉原图则删掉转换后的webp文件，这样就不会同时存在两张图片了

**Comment by smallSohoSolo** [comment]
这个问题我们之前遇到过就是gradle 运行中强制被kill 掉，本质上解决不了。。。正常停止不会有问题
