### ISSUE TITLE
raw文件夹图片没有被压缩

### ISSUE THREAD

**Issue by liuqingdada** [smallSohoSolo/McImage#71]
下面是我使用的配置
McImageConfig {
    // 是否检测图片大小，默认为true
    isCheckSize false
    // 优化类型，可选"ConvertWebp"，"Compress"，转换为webp或原图压缩，默认Compress，
    // 使用ConvertWep需要min sdk >= 18.但是压缩效果更好
    optimizeType "ConvertWebp"
    // debug下是否可用，default true
    enableWhenDebug false
    // 是否检测大像素图片，default true
    isCheckPixels false
    mctoolsDir "$rootDir"
    // 是否支持带有透明度的webp，default false, 带有透明图的图片会进行压缩
    isSupportAlphaWebp true
    mctoolsDir "$rootDir"
}

**Comment by smallSohoSolo** [comment]
raw 不压缩，这里面的文件业务上来讲是比较特殊的
